.PHONY: clean

all: dijkstra_1 dijkstra_2 network_delay_time_1 network_delay_time_2

dijkstra_1: dijkstra_1.c
	gcc -o dijkstra_1 dijkstra_1.c

dijkstra_2: dijkstra_2.c
	gcc -o dijkstra_2 dijkstra_2.c

network_delay_time_1: network_delay_time_1.c
	gcc -o network_delay_time_1 network_delay_time_1.c

network_delay_time_2: network_delay_time_2.c
	gcc -o network_delay_time_2 network_delay_time_2.c

clean:
	rm -f dijkstra_1 dijkstra_2 network_delay_time_1 network_delay_time_2
